export interface FirewallConfig {
  enabled: boolean;
  rules: FirewallRule[];
}

export interface FirewallRule {
  id: string;
  name: string;
  source: string;
  destination: string;
  protocol: string;
  action: string;
  enabled: boolean;
}

// For new rules, id is generated by backend
export type NewFirewallRule = Omit<FirewallRule, "id">;

// For CGI payloads (src_ip, dest_ip, proto, target)
export interface RawFirewallRule {
  id?: string;
  name: string;
  src_ip: string;
  dest_ip: string;
  proto: string;
  target: string;
  enabled: boolean;
  src?: string; // e.g., "lan"
  dest?: string; // e.g., "wan"
}

// For deletion payloads
export interface DeleteFirewallRule {
  id: string;
}