#!/bin/sh /etc/rc.common
START=99
STOP=10

USE_PROCD=1
PROG=/usr/sbin/packet-analyzerd

start_service() {
  procd_open_instance
  procd_set_param command "$PROG"
  procd_set_param respawn 3600 5 5
  procd_close_instance
}
